### ISSUE TITLE
Crash opening achievement GUI

### ISSUE THREAD

**Issue by KappaKiddie** [modmuss50/FTB-Achievements-Issues#2]
Crash report: https://pastebin.com/KVsXAruQ

**Comment by modmuss50** [comment]
Your not using it with the correct mod pack. This isn't supported.

**Comment by KappaKiddie** [comment]
SF3 Challenges isn't supported? LuL

**Comment by modmuss50** [comment]
The config had been changed in some way. The crash has been fixed anyway.

**Comment by KappaKiddie** [comment]
Optifine maybe?
