### ISSUE TITLE
super fast run speed

### ISSUE THREAD

**Issue by stevojhall** [modmuss50/FTB-Achievements-Issues#3]
hi have an issue with latest release (FTB-Achievements-1.1.1.151-universal.jar) with a fresh install (non edited config yet as was just testing to make sure mod worked and loaded) i can walk or run around on flat surface super fast, i dont know if it is a mod conflict but with this mod disabled i return to normal speed.

running around super fast is great and all but is impractical esp around lava or traps

this is with latest 3 versions of forge

**Comment by modmuss50** [comment]
The mod isn't designed to be used outside of the FTB challenges map. You will not get support. I recommend uninstalling the mod.

**Comment by stevojhall** [comment]
Oh right thanks totally got the wrong end of the stick for this mod lol, this must be what was causing the fast running for ftb sky factory challenge map.
